"""add facebook oauth columns to tenant_credentials

Revision ID: 7aa18cc4ec8e
Revises: 6854d88a1a66
Create Date: 2026-07-09 22:39:20.669638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa18cc4ec8e'
down_revision: Union[str, None] = '6854d88a1a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_credentials', sa.Column('facebook_user_id', sa.String(length=255), nullable=True))
    op.add_column('tenant_credentials', sa.Column('page_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_credentials', 'page_id')
    op.drop_column('tenant_credentials', 'facebook_user_id')
    # ### end Alembic commands ###
