"""add shopify columns to products

Revision ID: a1b2c3d4e5f6
Revises: 7aa18cc4ec8e
Create Date: 2026-07-13 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '7aa18cc4ec8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('shopify_product_id', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('shopify_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('source', sa.String(length=20), server_default='manual', nullable=False))
    op.create_index('idx_products_shopify_id', 'products', ['tenant_id', 'shopify_product_id'], unique=True, postgresql_where='shopify_product_id IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_products_shopify_id', table_name='products', postgresql_where='shopify_product_id IS NOT NULL')
    op.drop_column('products', 'source')
    op.drop_column('products', 'shopify_synced_at')
    op.drop_column('products', 'shopify_product_id')
    # ### end Alembic commands ###